Repository AY2425S1-CS2103T-T11-2/tp, pull requests merged in 2024-10, with the labels that each got.

#58 Add Telegram as input and parse it
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Telegram.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/TelegramTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.High, type.Enhancement

#60 Add input and parsing of adding grades
  src/main/java/seedu/address/logic/commands/AddGradeCommand.java
  src/main/java/seedu/address/logic/parser/AddGradeCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/assignment/Assignment.java
  src/main/java/seedu/address/model/person/Person.java
  src/test/java/seedu/address/logic/commands/AddGradeCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddGradeCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/assignment/AssignmentTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
Labels: priority.High

#61 Update delete command to reference NAME
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
Labels: priority.High, type.Enhancement

#69 Add GitHub field to UI
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
Labels: priority.High, type.Task

#72 Add tests for GitHub class
  src/main/java/seedu/address/model/person/Github.java
  src/test/java/seedu/address/model/person/GithubTest.java
Labels: priority.High, type.Task

#74 Update usage text for DeleteCommand
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
Labels: priority.High

#78 Update user guide for add and edit command
  docs/UserGuide.md
Labels: priority.Medium, type.Enhancement

#82 Update User Guide to add telegram fields
  docs/UserGuide.md
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
Labels: priority.Medium, type.Task

#83 Add predefined assignment database
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyUserPrefs.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/model/assignment/PredefinedAssignment.java
  src/main/java/seedu/address/model/assignment/PredefinedAssignmentsData.java
  src/main/java/seedu/address/model/assignment/ReadOnlyPredefinedAssignmentsData.java
  src/main/java/seedu/address/storage/Storage.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/main/java/seedu/address/storage/assignment/JsonAdaptedPredefinedAssignment.java
  src/main/java/seedu/address/storage/assignment/JsonPredefinedAssignmentDataStorage.java
  src/main/java/seedu/address/storage/assignment/JsonSerializablePredefinedAssignmentData.java
  src/main/java/seedu/address/storage/assignment/PredefinedAssignmentDataStorage.java
  src/test/data/AssignmentTest/PredefinedAssignmentDuplicate.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddGradeCommandTest.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
  src/test/java/seedu/address/storage/assignment/JsonAdaptedPredefinedAssignmentTest.java
  src/test/java/seedu/address/storage/assignment/JsonPredefinedAssignmentDataStorageTest.java
  src/test/java/seedu/address/storage/assignment/JsonSerializablePredefinedAssignmentDataTest.java
Labels: priority.High

#86 New feature: filter contacts by tags
  src/main/java/seedu/address/logic/commands/FilterCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/FilterCommandParser.java
  src/main/java/seedu/address/model/person/TagContainsKeywordsPredicate.java
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/FilterCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/FilterCommandParserTest.java
  src/test/java/seedu/address/model/tag/TagContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.High, type.Story

#90 Update user guide for delete and filter command
  docs/UserGuide.md
Labels: priority.High

#85 Add open URL button to help page
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/resources/view/HelpWindow.css
  src/main/resources/view/HelpWindow.fxml
Labels: priority.Medium, type.Enhancement

#93 Add sample assignment data if file not found
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/model/assignment/PredefinedAssignmentsData.java
  src/main/java/seedu/address/model/util/SampleAssignmentsUtil.java
  src/test/java/seedu/address/logic/commands/AddGradeCommandTest.java
  src/test/java/seedu/address/model/assignment/PredefinedAssignmentsDataTest.java
Labels: priority.Medium

#105 Update user guide for github command
  docs/UserGuide.md
Labels: priority.Medium, type.Enhancement

#98 Implement view command to show details
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/ViewCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ViewCommandParser.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/ViewWindow.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/ViewWindow.fxml
  src/test/java/seedu/address/logic/commands/CommandResultTest.java
  src/test/java/seedu/address/logic/commands/ViewCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/ViewCommandParserTest.java
Labels: priority.High

#103 Branch update help command to functional browser
  docs/UserGuide.md
  docs/images/helpMessage.png
  src/main/java/seedu/address/ui/HelpWindow.java
Labels: type.Bug, priority.High

#107 Update user guide for view command
  docs/UserGuide.md
Labels: priority.Medium

#106 Add sort command to sort the displayed list
  src/main/java/seedu/address/logic/commands/FilterCommand.java
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/SortCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Github.java
  src/main/java/seedu/address/model/person/Name.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Telegram.java
  src/main/java/seedu/address/model/person/comparator/ComparatorManager.java
  src/main/java/seedu/address/model/person/comparator/PersonComparator.java
  src/main/java/seedu/address/model/person/comparator/PersonComparatorByGithub.java
  src/main/java/seedu/address/model/person/comparator/PersonComparatorByName.java
  src/main/java/seedu/address/model/person/comparator/PersonComparatorByTelegram.java
  src/main/java/seedu/address/model/person/comparator/SortField.java
  src/main/java/seedu/address/model/person/comparator/SortOrder.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/GitHubCommandTest.java
  src/test/java/seedu/address/logic/commands/SortCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/SortCommandParserTest.java
  src/test/java/seedu/address/model/person/GithubTest.java
  src/test/java/seedu/address/model/person/NameTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/TelegramTest.java
  src/test/java/seedu/address/model/person/comparator/ComparatorManagerTest.java
  src/test/java/seedu/address/model/person/comparator/PersonComparatorByGithubTest.java
  src/test/java/seedu/address/model/person/comparator/PersonComparatorByNameTest.java
  src/test/java/seedu/address/model/person/comparator/PersonComparatorByTelegramTest.java
Labels: priority.High, type.Story

#112 Edit user guide to incorporate mark and unmark command
  docs/UserGuide.md
  docs/images/markViswaPresent.png
  docs/images/unmarkViswa.png
Labels: priority.High, type.Enhancement

#118 Enable assertions to file
  build.gradle
Labels: priority.High, type.Task

#123 Update user guide for sort command
  docs/UserGuide.md
Labels: priority.High, type.Enhancement

#125 Update sequence diagram in architecture
  docs/DeveloperGuide.md
  docs/diagrams/ArchitectureSequenceDiagram.puml
Labels: priority.Medium

#110 Add mark and unmark command
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/MarkCommand.java
  src/main/java/seedu/address/logic/commands/UnmarkCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/MarkCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/UnmarkCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/data/testExport.csv
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/GitHubCommandTest.java
  src/test/java/seedu/address/logic/commands/MarkCommandTest.java
  src/test/java/seedu/address/logic/commands/UnmarkCommandTest.java
  src/test/java/seedu/address/logic/parser/MarkCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/logic/parser/UnmarkCommandParserTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.Medium, severity.Medium, type.Task

#117 Update Model UML class diagram
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
Labels: priority.High, type.Enhancement

#134 Edit UI and user guide for easier reference
  docs/UserGuide.md
  docs/images/markPresent.png
  docs/images/markViswaPresent.png
  docs/images/unmarkStudent.png
  docs/images/unmarkViswa.png
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/DarkTheme.css
Labels: priority.High, type.Enhancement

#132 Update add grade command to accept multiple assignments
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/commands/AddGradeCommand.java
  src/main/java/seedu/address/logic/commands/ExportCommand.java
  src/main/java/seedu/address/logic/commands/ImportCommand.java
  src/main/java/seedu/address/logic/parser/AddGradeCommandParser.java
  src/main/java/seedu/address/model/assignment/Assignment.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/test/data/testExport.csv
  src/test/data/testImport.csv
  src/test/java/seedu/address/logic/commands/AddGradeCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/model/assignment/AssignmentTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
Labels: priority.High

#140 Refine UI of the app
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/AddGradeCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/ExportCommand.java
  src/main/java/seedu/address/logic/commands/ImportCommand.java
  src/main/java/seedu/address/logic/commands/MarkCommand.java
  src/main/java/seedu/address/logic/commands/UnmarkCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Address.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/java/seedu/address/ui/ViewWindow.java
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonListCard.fxml
  src/main/resources/view/ViewWindow.fxml
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/data/invalidImport.csv
  src/test/data/testExport.csv
  src/test/data/testImport.csv
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/person/AddressTest.java
  src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/TelegramTest.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.Medium, type.Enhancement
