Repository AY2425S1-CS2103T-T11-2/tp, pull requests merged in 2024-09, with the labels that each got.

#16 Add Javier's photo
  docs/images/incogdino.png
Labels: priority.Medium, type.Task

#21 Update Wen Rui's section on AboutUs page
  docs/AboutUs.md
  docs/team/currynia.md
Labels: priority.High

#24 Update Javier's section on AboutUs page
  docs/AboutUs.md
  docs/team/incogdino.md
Labels: priority.Medium, type.Task

#23 Update Xiang Yu's section on AboutUs page
  docs/AboutUs.md
  docs/team/dessnowy.md
Labels: priority.High, type.Task

#40 Add Acknowledgement of original source code
  docs/index.md
Labels: priority.High, type.Task

#41 Update Github Actions build status badge to reflect team repo badge
  docs/index.md
Labels: priority.High, type.Task

#39 Add non functional requirements for developer guide
  docs/DeveloperGuide.md
Labels: priority.High, type.Story

#43 Update User Stories section in Developer Guide
  docs/DeveloperGuide.md
Labels: priority.High, type.Task

#44 Update readme (A4)
  docs/index.md
Labels: priority.High

#42 Update dg with use cases
  docs/DeveloperGuide.md
Labels: priority.High
