Repository AY2425S1-CS2103T-T11-2/tp, pull requests merged in 2024-11, with the labels that each got.

#138 Branch add command history
  docs/UserGuide.md
  src/main/java/seedu/address/storage/CommandHistory.java
  src/main/java/seedu/address/ui/CommandBox.java
  src/test/java/seedu/address/storage/CommandHistoryTest.java
Labels: priority.Medium, type.Enhancement

#162 Update user guide
  docs/UserGuide.md
Labels: alpha-bug

#177 Update GitHub command
  src/main/java/seedu/address/logic/commands/GitHubCommand.java
Labels: priority.Medium, alpha-bug

#178 Fix spacing in error messaage of sort command
  src/main/java/seedu/address/logic/commands/SortCommand.java
Labels: severity.VeryLow, alpha-bug

#179 Fix spacing in FilterCommand usage message
  src/main/java/seedu/address/logic/commands/FilterCommand.java
Labels: type.Bug, severity.VeryLow, alpha-bug

#143 Update addGrade user guide and feedback to user
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/AddGradeCommand.java
  src/main/java/seedu/address/logic/parser/AddGradeCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/assignment/PredefinedAssignment.java
  src/main/java/seedu/address/model/assignment/PredefinedAssignmentsData.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddGradeCommandTest.java
  src/test/java/seedu/address/logic/commands/GitHubCommandTest.java
  src/test/java/seedu/address/logic/parser/AddGradeCommandParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/assignment/PredefinedAssignmentTest.java
  src/test/java/seedu/address/model/assignment/PredefinedAssignmentsDataTest.java
Labels: type.Enhancement

#180 Update edit command
  src/main/java/seedu/address/logic/commands/EditCommand.java
Labels: type.Bug, priority.High, alpha-bug

#181 Improve error message for invalid person
  src/main/java/seedu/address/logic/Messages.java
Labels: severity.Low, alpha-bug

#183 Update user guide
  docs/UserGuide.md
Labels: priority.Medium, type.Enhancement

#187 Change edit command to account for attendance and UI changes
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/ui/ViewWindow.java
  src/main/resources/view/DarkTheme.css
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
Labels: priority.High

#196 Update add command error message
  docs/UserGuide.md
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Github.java
  src/test/java/seedu/address/model/person/GithubTest.java
Labels: type.Bug, priority.High, type.Enhancement, alpha-bug

#199 Update help window to provide more details
  docs/UserGuide.md
  docs/images/helpMessage.png
  src/main/java/seedu/address/ui/CommandDetailCard.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/resources/view/CommandDetailCard.css
  src/main/resources/view/CommandDetailCard.fxml
  src/main/resources/view/HelpWindow.fxml
Labels: priority.Medium, type.Enhancement

#195 Update view to persist across commands and persist assignments for edit
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/ViewCommand.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/logic/commands/CommandResultTest.java
  src/test/java/seedu/address/logic/commands/ViewCommandTest.java
Labels: alpha-bug

#207 Fix addGrade to display error on gui
  src/main/java/seedu/address/logic/commands/AddGradeCommand.java
  src/main/java/seedu/address/logic/parser/AddGradeCommandParser.java
  src/test/java/seedu/address/logic/commands/AddGradeCommandTest.java
  src/test/java/seedu/address/logic/commands/RemoveGradeCommandTest.java
  src/test/java/seedu/address/logic/parser/AddGradeCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
Labels: alpha-bug

#211 Branch update tag error message
  docs/UserGuide.md
  src/main/java/seedu/address/model/tag/Tag.java
Labels: priority.High, type.Enhancement

#216 Abstract constants from certain methods
  src/main/java/seedu/address/commons/core/FunctionalBrowser.java
  src/main/java/seedu/address/logic/commands/ImportCommand.java
  src/main/java/seedu/address/logic/commands/ViewCommand.java
  src/main/java/seedu/address/logic/parser/CsvRowParser.java
  src/test/java/seedu/address/logic/commands/ImportCommandTest.java
Labels: priority.High, type.Enhancement

#213 SortCommand should make sortOrder to be default
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/parser/SortCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/comparator/SortField.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/SortCommandTest.java
  src/test/java/seedu/address/logic/parser/SortCommandParserTest.java
Labels: type.Enhancement, alpha-bug

#222 Remove Phone, Address from user and developer Guide
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
Labels: priority.High, alpha-bug

#219 Update screenshots of commands in the user guide
  docs/UserGuide.md
  docs/images/excelKnownIssue.png
  docs/images/githubUsage.png
  docs/images/helpMessage.png
  docs/images/viewWindowScreenshot.png
Labels: priority.Medium, type.Enhancement

#224 Remove unused dev guide
  docs/DeveloperGuide.md
Labels: priority.High, type.Enhancement

#231 Change Tag to be case insensitive
  src/main/java/seedu/address/model/tag/Tag.java
Labels: priority.Medium, alpha-bug

#232 Change command prefix to have a alternate form
  src/main/java/seedu/address/logic/parser/ArgumentMultimap.java
  src/main/java/seedu/address/logic/parser/ArgumentTokenizer.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/Prefix.java
  src/test/data/testExport.csv
  src/test/java/seedu/address/logic/parser/ArgumentTokenizerTest.java
Labels: priority.High, alpha-bug

#234 Change command word to be case insensitive
  src/main/java/seedu/address/logic/commands/AddGradeCommand.java
  src/main/java/seedu/address/logic/commands/RemoveGradeCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
Labels: priority.Medium, alpha-bug

#237 Update screenshots for user guide
  docs/images/githubUsage.png
  docs/images/viewWindowScreenshot.png
Labels: priority.Medium, type.Enhancement

#238 Update user guide
  docs/UserGuide.md
Labels: priority.High

#248 Rename storgae file to konTActs.json
  docs/UserGuide.md
  src/main/java/seedu/address/model/UserPrefs.java
  src/test/data/JsonUserPrefsStorageTest/ExtraValuesUserPref.json
  src/test/data/JsonUserPrefsStorageTest/TypicalUserPref.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/storage/JsonUserPrefsStorageTest.java
Labels: priority.High, alpha-bug

#240 Add short form for commands
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/AddGradeCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/ExportCommand.java
  src/main/java/seedu/address/logic/commands/FilterCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/GitHubCommand.java
  src/main/java/seedu/address/logic/commands/ImportCommand.java
  src/main/java/seedu/address/logic/commands/MarkCommand.java
  src/main/java/seedu/address/logic/commands/RemoveGradeCommand.java
  src/main/java/seedu/address/logic/commands/UnmarkCommand.java
  src/main/java/seedu/address/logic/commands/ViewCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
Labels: priority.High, type.Enhancement

#242 Branch update quick start
  docs/UserGuide.md
  docs/images/quickStartLaunchScreenshot.png
  docs/images/quickStartResultScreenshot.png
Labels: priority.Medium

#251 Rename jar file
  build.gradle
Labels: priority.Medium, alpha-bug

#253 Update logo of KonTActs
  docs/UserGuide.md
  docs/images/kontactsLogo.png
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/images/kontactsLogo.png
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/commons/util/AppUtilTest.java
Labels: priority.High

#261 Remove tutorial section
  docs/_markbind/layouts/default.md
Labels: priority.High

#260 Branch update home page
  docs/images/homePage.png
  docs/index.md
Labels: priority.High

#259 Update screenshots of user guide
  docs/UserGuide.md
  docs/images/filterFriendsTagByFilter.png
  docs/images/findAlexCharlotte.png
  docs/images/findFriendsTagByFilter.png
  docs/images/githubUsage.png
  docs/images/markAlexAbsent.png
  docs/images/markAlexPresent.png
  docs/images/quickStartLaunchScreenshot.png
  docs/images/quickStartResultScreenshot.png
  docs/images/sortByNameDesc.png
  docs/images/sortReset.png
Labels: priority.High

#262 Update Readme
  README.md
Labels: priority.High

#266 Update ReadMe
  README.md
Labels: priority.High

#269 Minor update to ug and dg
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: priority.High, alpha-bug

#265 Fix bug for view command
  src/main/java/seedu/address/logic/commands/ViewCommand.java
  src/main/java/seedu/address/ui/MainWindow.java
Labels: priority.High, alpha-bug

#272 Improve error message for sort
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/SortCommandParser.java
  src/test/java/seedu/address/logic/parser/SortCommandParserTest.java
Labels: priority.High, alpha-bug

#274 Update command usage message
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/AddGradeCommand.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/FilterCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/GitHubCommand.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/MarkCommand.java
  src/main/java/seedu/address/logic/commands/RemoveGradeCommand.java
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/commands/UnmarkCommand.java
  src/main/java/seedu/address/logic/commands/ViewCommand.java
  src/main/java/seedu/address/ui/HelpWindow.java
Labels: priority.High, type.Enhancement

#278 Update Readme
  README.md
Labels: priority.High, alpha-bug

#280 Remove error line
  docs/UserGuide.md
Labels: priority.High, alpha-bug

#281 Update assignment json to handle null values
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/storage/assignment/JsonAdaptedPredefinedAssignment.java
  src/main/java/seedu/address/storage/assignment/JsonSerializablePredefinedAssignmentData.java
  src/test/data/AssignmentTest/MissingName.json
  src/test/data/AssignmentTest/MissingScore.json
  src/test/java/seedu/address/storage/assignment/JsonPredefinedAssignmentDataStorageTest.java
Labels: alpha-bug

#282 Update view command
  src/main/java/seedu/address/logic/commands/ViewCommand.java
Labels: priority.High, alpha-bug

#344 Update import ug
  docs/UserGuide.md
Labels: priority.High

#343 Update known issues in user guide to reflect why certain fields are not on shown in person card
  docs/UserGuide.md
Labels: priority.High

#346 Update ug for addgrade and csv
  docs/UserGuide.md
  docs/images/validCSV1.png
Labels: UG

#350 Update input for unused parameters
  docs/UserGuide.md
Labels: priority.Medium, UG

#349 Update Sort user guide
  docs/UserGuide.md
Labels: priority.Medium, UG

#348 Add warnings to clear command
  docs/UserGuide.md
Labels: priority.Medium

#351 Update user guide
  docs/UserGuide.md
Labels: priority.High, UG

#353 Update use cases
  docs/DeveloperGuide.md
Labels: DG

#352 Fix view overflow and scrolling issues
  src/main/java/seedu/address/ui/ViewWindow.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/ViewWindow.fxml
Labels: priority.High

#355 Update addgrade ug path
  docs/UserGuide.md
Labels: UG

#360 Update user guide
  docs/UserGuide.md
Labels: priority.High, UG

#359 Update known issues
  docs/UserGuide.md
Labels: priority.Medium, UG

#358 Fix csv import
  src/main/java/seedu/address/logic/parser/CsvAssignmentParser.java
Labels: alpha-bug

#362 Branch update ug
  docs/UserGuide.md
Labels: UG

#363 Update email restrictions
  docs/UserGuide.md
  src/main/java/seedu/address/model/person/Email.java
Labels: priority.High, UG

#364 Update links in DG
  docs/DeveloperGuide.md
Labels: priority.High, DG

#366 Update user guide
  docs/UserGuide.md
Labels: UG

#356 Update user and developer guide
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/updatedQuickStartLaunchScreenshot.png
Labels: priority.High

#357 Add UG details for import-export
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: UG

#373 Add backtick to csv header
  docs/UserGuide.md
Labels: UG

#374 Add the before ~
  docs/UserGuide.md
Labels: UG

#371 Format user guide
  docs/UserGuide.md
  docs/images/markAlexAbsent.png
  docs/images/markAlexPresent.png
  docs/images/sortByNameDesc.png
  docs/images/sortReset.png
Labels: priority.High, UG

#370 Update use cases to match implementation
  docs/DeveloperGuide.md
Labels: priority.High, DG

#367 Update manual test cases for dg
  docs/DeveloperGuide.md
Labels: DG

#376 Improve code quality
  src/main/java/seedu/address/commons/core/FunctionalBrowser.java
Labels: priority.Medium

#378 Add acknowledgement
  docs/DeveloperGuide.md
Labels: DG

#379 Add AddCommand implementation
  docs/DeveloperGuide.md
  docs/diagrams/addSequenceDiagram.puml
Labels: priority.High

#381 Implementation for addgrade
  docs/DeveloperGuide.md
  docs/diagrams/AddGradeImpl.puml
Labels: DG
